algoritmo "média aritmética"
// Função :
// Autor :
// Data : 07/03/2024
// Seção de Declarações 

var
nota1, nota2, nota3, nota4, mediaf: real

inicio
// Seção de Comandos
escreva("Informe sua nota 1: ")
leia(nota1)
escreva("Informe sua nota 2: ")
leia(nota2)
escreva("Informe sua nota 3: ")
leia(nota3)
escreva("Inforem sua nota 4: ")
leia(nota4)

mediaf <- (nota1 + nota2 + nota3 + nota4) / 4

escreva("Sua média final é: ", mediaf)
fimalgoritmo
