algoritmo "semnome"
// Função :
// Autor :
// Data : 28/03/2024
// Seção de Declarações 
var
num, maior: inteiro


inicio
// Seção de Comandos 
escreval("Digite um número: ")
leia(num)

enquanto (num <> 0) faca
escreval("Informe um número: ")
leia(num)


se ( num > maior) entao
  maior <- num
fimse
fimenquanto
escreva("O maior número digitado é: ", maior)





fimalgoritmo
