algoritmo "semnome"
// Função :
// Autor :
// Data : 28/03/2024
// Seção de Declarações 
var
cont, x: inteiro
f: literal


inicio
// Seção de Comandos 

enquanto (cont <= 10) faca
  escreval("Dentro do enquanto com cont: ", cont)
  cont <- cont + 1
fimenquanto

enquanto (x <> 1 ) faca
  escreva("informe o valor de x: ")
  leia(x)
fimenquanto

enquanto (f <> "S") faca
  escreva ("Deseja parar: S-Sim N-Não")
  leia (f)
fimenquanto


fimalgoritmo
